### PR TITLE
Logo patch 01

### PR DESCRIPTION
**Pull request by flofrie**
Improved design of Autonity logo, with changes to design, as well as colour scheme that works both in normal and dark modes (since Github users may view the repo & readme in dark mode)

Deleted previous "autonity-logo.svg".

### CODE REVIEW

**Comment by flofrie** [comment]
I recommend (if at all possible as per policy) merging this into `master` as soon as possible, since currently the logo in the README does not show up properly when using dark mode. Also, this is the most current logo design.

**Comment by cmjc** [comment]
> I recommend (if at all possible as per policy) merging this into `master` as soon as possible, since currently the logo in the README does not show up properly when using dark mode. Also, this is the most current logo design.

Also, a commit with an edit to README to fix links to docs, minor text edits.

**Comment by flofrie** [comment]
@yazzaoui , @aiman , please review and merge. Some necessary updates to README and Autonity logo; therefore this is against `master`.

**Comment by flofrie** [comment]
@yazzaoui , @Jason-Zhangxin-Chen , you are designated reviewers, but it seems Github has run its checks and allows me to merge ... so shall I simply do that now, or wait for your explicit approval?

**Review by Jason-Zhangxin-Chen — APPROVED** [review]
LGTM.

**Pull request merged**
