### PR TITLE
Optimize execution layer topology

### PR DESCRIPTION
**Pull request by tbssajal**
- Runtime optimization of execution layer network topology to support $\text{MaxCommitteeSize} = 1000$
- Improve execution layer network topology construction to have $\text{diameter} \leq 4 \ and \ \text{degree} \leq 24$

### CODE REVIEW

**Review by lorenzo-dev1 — APPROVED** [review]
LGTM!

Is there a test that checks that no node remains isolated even when we have multiple components?

**Review by yazzaoui — APPROVED** [review]
LGT

**Comment by tbssajal** [comment]
> LGTM!
> 
> Is there a test that checks that no node remains isolated even when we have multiple components?

I think I have it in tests, but I will confirm!

**Comment by tbssajal** [comment]
> LGTM!
> 
> Is there a test that checks that no node remains isolated even when we have multiple components?

TestGraphDiamter does that by checking the shortest distance between each pair of nodes. If some node is isolated, then the shortest distance for some pair will not be determined.

**Comment by tbssajal** [comment]
[degreeCount.txt](https://github.com/user-attachments/files/15884829/degreeCount.txt)
Degree count for all nodes for committee size = 50, 64,65,100,200,500,1000

**Pull request merged**
