### PR TITLE
Add tests for latest consensus fixes

### PR DESCRIPTION
**Pull request by lorenzo-dev1**
- Add tests for https://github.com/autonity/autonity/pull/935
- fixes some other e2e tests (we were not checking the return value of some method calls)

### CODE REVIEW

**Review by vpiyush — APPROVED** [review]
LGTM

**Comment by lorenzo-dev1** [comment]
funny situation, executing `TestNodeAlreadyHasProposedBlock` makes `TestStartStopAllNodesInParallel` become racey

**Comment by lorenzo-dev1** [comment]
> > funny situation, executing `TestNodeAlreadyHasProposedBlock` makes `TestStartStopAllNodesInParallel` become racey
> 
> Did you try running tests in parallel locallly? probably there is a race in test code itself

There was indeed a race condition in `TestNodeAlreadyHasProposedBlock` . fixed in https://github.com/autonity/autonity/pull/938/commits/a6f6ed8b377b6d153f0f0fe923d9feb10540b76f

**Comment by lorenzo-dev1** [comment]
Changes incorporated in https://github.com/autonity/autonity/pull/937

**Pull request closed without merging**
