### PR TITLE
JSON-RPC tests

### PR DESCRIPTION
**Pull request by szemate**
This pull request adds a framework for black-box JSON-RPC tests for Autonity.

It includes a number of tests for the `eth` namespace, I keep adding new tests to this branch continuously.

### CODE REVIEW

**Review by Jason-Zhangxin-Chen — COMMENTED** [review]
@szemate , thank you for your great work, and your professional skill in test and python would help us a lots. I would schedule a call with you to discuss the integration of this with docker e2e test.

**Review by Jason-Zhangxin-Chen — APPROVED** [review]
LGTM, Thank you so much,  Matez.

**Comment by aiman** [comment]
I ran the tests with `./run-tests-in-vm` and all `27` tests are passing :heavy_check_mark:

**Comment by szemate** [comment]
The API coverage is 17/39 (44%) based on https://ethereum.org/en/developers/docs/apis/json-rpc/

**Pull request merged**
