### PR TITLE
add err check for sb.Finalize that was un-checked potentially causing issues

### PR DESCRIPTION
**Pull request by thomasmodeneis**
Hi,

I was reading up the code on the Tendermint backend and noticed a small issue that probably escaped from your eye. So I opened a small PR in order to contribute back to this amazing project!

Please let me know if it is of any relevance to you or not.

Note: This is a re-creation of the #738 as instructed.

### CODE REVIEW

**Review by Jason-Zhangxin-Chen — COMMENTED** [review]
Hi Thomas, thank you so much for your contributions on this master branch. We accutally also address this problem weeks ago, and it is fixed in our develop branch "develop". And the correction was release at autonity 0.7.1.  Master branch will be synced soon.

**Comment by piersy** [comment]
Hi @Jason-Zhangxin-Chen, I don't think we have addressed this, see that we still overwrite the error from Finalize:

https://github.com/clearmatics/autonity/blob/7731c4e14ff498b3de5d3432b26a4146776ef932/consensus/tendermint/backend/backend.go#L327-L332

@thomasmodeneis I can see that our github actions tests are still not running, so I'm going to investigate further. Sorry to have made you recreate this PR needlessly.

**Comment by thomasmodeneis** [comment]
> Hi Thomas, thank you so much for your contributions on this master branch. We accutally also address this problem weeks ago, and it is fixed in our develop branch "develop". And the correction was release at autonity 0.7.1. Master branch will be synced soon.



> Hi @Jason-Zhangxin-Chen, I don't think we have addressed this, see that we still overwrite the error from Finalize:
> 
> https://github.com/clearmatics/autonity/blob/7731c4e14ff498b3de5d3432b26a4146776ef932/consensus/tendermint/backend/backend.go#L327-L332
> 
> @thomasmodeneis I can see that our github actions tests are still not running, so I'm going to investigate further. Sorry to have made you recreate this PR needlessly.

Sure, no problem. The CI not running is indeed something weird. Let me know if I can be any helpful.

**Comment by Jason-Zhangxin-Chen** [comment]
> Hi @Jason-Zhangxin-Chen, I don't think we have addressed this, see that we still overwrite the error from Finalize:
> 
> https://github.com/clearmatics/autonity/blob/7731c4e14ff498b3de5d3432b26a4146776ef932/consensus/tendermint/backend/backend.go#L327-L332
> 
> @thomasmodeneis I can see that our github actions tests are still not running, so I'm going to investigate further. Sorry to have made you recreate this PR needlessly.

@piersy , you are right, the error indeed should be checked.

**Comment by piersy** [comment]
Hi @thomasmodeneis, we have now merged changes to our develop branch that should allow github actions checks to run on this PR, but the PR needs to be updated, on our own PRs there is a button to `update branch` but I cannot see that here, so please could you update this PR and then I hope we can merge it.

**Comment by thomasmodeneis** [comment]
> Hi @thomasmodeneis, we have now merged changes to our develop branch that should allow github actions checks to run on this PR, but the PR needs to be updated, on our own PRs there is a button to `update branch` but I cannot see that here, so please could you update this PR and then I hope we can merge it.

Great, it seems to be working now :+1:

**Comment by thomasmodeneis** [comment]
There seems to be an error: `Error:     upon_condition_test.go:457: Broken for some random values https://github.com/clearmatics/autonity/issues/715`, probably need to be restarted

**Comment by thomasmodeneis** [comment]
ping, can someone re-run the job ? :)

**Comment by yazzaoui** [comment]
Depreciated, closing.

**Pull request closed without merging**
